USE [master]
GO

/****** Object:  Database [inchiriat_masini]    Script Date: 1/27/2022 7:49:53 PM ******/
CREATE DATABASE [inchiriat_masini]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'inchiriat_masini', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\inchiriat_masini.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'inchiriat_masini_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\inchiriat_masini_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [inchiriat_masini] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [inchiriat_masini].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [inchiriat_masini] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [inchiriat_masini] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [inchiriat_masini] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [inchiriat_masini] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [inchiriat_masini] SET ARITHABORT OFF 
GO

ALTER DATABASE [inchiriat_masini] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [inchiriat_masini] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [inchiriat_masini] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [inchiriat_masini] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [inchiriat_masini] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [inchiriat_masini] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [inchiriat_masini] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [inchiriat_masini] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [inchiriat_masini] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [inchiriat_masini] SET  DISABLE_BROKER 
GO

ALTER DATABASE [inchiriat_masini] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [inchiriat_masini] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [inchiriat_masini] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [inchiriat_masini] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [inchiriat_masini] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [inchiriat_masini] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [inchiriat_masini] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [inchiriat_masini] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [inchiriat_masini] SET  MULTI_USER 
GO

ALTER DATABASE [inchiriat_masini] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [inchiriat_masini] SET DB_CHAINING OFF 
GO

ALTER DATABASE [inchiriat_masini] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [inchiriat_masini] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [inchiriat_masini] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [inchiriat_masini] SET  READ_WRITE 
GO


